### PR TITLE
build!: drop node 10, update typescript to 4.6.3

### PR DESCRIPTION
**Pull request by ddelgrosso1**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com//issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Review by summer-ji-eng — APPROVED** [review]

**Review by sofisl — APPROVED** [review]

**Comment by sofisl** [comment]
Just want to confirm, did you add a legacy tag here as well?

**Comment by ddelgrosso1** [comment]
@sofisl yes I created a legacy-10 tag.

**Comment by sofisl** [comment]
Cool! Also, I think we can bump to mocha 10 in this PR. Thank you!

**Comment by ddelgrosso1** [comment]
Mocha 10 drops support for Node 12. I think we are stuck with 9.x. https://github.com/mochajs/mocha/pull/4845

**Pull request merged**
