### PR TITLE
fix: correctly set compress/gzip option when false

### LINKED ISSUE #94: Request option gzip=false is not handled correctly
[@google-cloud/bigquery](https://www.npmjs.com/package/@google-cloud/bigquery) relies on [@google-cloud/common](https://www.npmjs.com/package/@google-cloud/common) for requests, and then uses teeny-request.

I wanted to disable gzip for all requests, but it turns out that the gzip variable is not handled correctly and it never end up being assigned.

[File index.ts -> Ln 92](https://github.com/googleapis/teeny-request/blob/master/src/index.ts#L92).

```javascript
function requestToFetchOptions(reqOpts: Options) {
  const options: f.RequestInit = {
    method: reqOpts.method || 'GET',
    ...(reqOpts.timeout && {timeout: reqOpts.timeout}),
    ...(reqOpts.gzip && {compress: reqOpts.gzip}),
  };

  // ...
}
```

If reqOpts.gzip is false, the code after && will be never executed, and never assigned.

#### Environment details

  - OS:
  - Node.js version: v12.11.1
  - npm version: 6.11.3
  - `teeny-request` version: 5.3.0

#### Steps to reproduce

```javascript
teenyRequest({ uri: '...', gzip: false });
```

or

```javascript
let bigquery = new BigQuery(options);

bigquery.interceptors.push({
  request: function (reqOpts) {
    reqOpts.gzip = false;
    return reqOpts
  }
});
```

### PR DESCRIPTION
**Pull request by callmehiphop**
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #94 🦕

### CODE REVIEW

**Comment by callmehiphop** [comment]
I didn't include unit tests because currently there isn't a solid way to test that request options get converted to the fetch counterpart correctly. My initial instinct is use `proxyquire` to stub `fetch` but I'm not sure if we're deliberately avoiding it. @bcoe @JustinBeckwith what kind of feels do you have here?

**Comment by JustinBeckwith** [comment]
Generally I like to avoid `proxyquire` and go all the way down to the network request, and use `nock` to validate the final output looks like what I expect.

**Comment by bcoe** [comment]
:wave: I agree with @JustinBeckwith on this one, I think that `nock` would be a great choice to confirm headers are set as expected.

**Comment by callmehiphop** [comment]
@bcoe @JustinBeckwith SGTM, went ahead and created a couple tests if I could bother either/both of you to take a look!

**Pull request merged**
