### PR TITLE
chore(docs): update badge link in README

### LINKED ISSUE #174: Broken badge link and svg
**Is your feature request related to a problem? Please describe.**
The Badge svg show unknown and link is not found. They point the old personal domain instead of googleapis
 **Describe the solution you'd like**
Update link and svg

### PR DESCRIPTION
**Pull request by davidkhala**
Fix broken badge link and svg

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com//issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #174  🦕

### CODE REVIEW

**Comment by davidkhala** [comment]
OOP, it seems I have to follow all the steps even for a simple doc change.

**Comment by davidkhala** [comment]
@googlebot I signed it!

**Comment by stephenplusplus** [comment]
Thanks for going through all of that for such a simple change! After CI gives us the all-green, we can merge this in. Thanks again for catching that and sending the fix.

**Comment by davidkhala** [comment]
Personal curiosity, why the automated build will last for several days? Does it mean this is still waiting in a long build queue?

**Comment by stephenplusplus** [comment]
> Personal curiosity, why the automated build will last for several days? Does it mean this is still waiting in a long build queue?

Sometimes, we are in a big queue, but in this case, it could be that our internal test runner (Kokoro) fell asleep and needs a quick kick. I'm afraid I can't be more specific-- I really don't know why it flops on us sometime :( Kicking complete, though, so let's see if that helps!

**Pull request merged**
