### PR TITLE
fix: Buffer is allow as body without encoding to string

### PR DESCRIPTION
**Pull request by alexpts**
Added support for working with a Buffer as body of request

### CODE REVIEW

**Comment by alexpts** [comment]
@googlebot I signed it!

**Review by JustinBeckwith — APPROVED** [review]
This is great - thanks!

**Comment by alexpts** [comment]
The release of a new version will help me a lot. 
@JustinBeckwith can you release new npm version 7.1.0?

**Comment by JustinBeckwith** [comment]
Sure, we need to land some of the test coverage I added in #226 first though.

**Pull request merged**
